const API_BASE = import.meta.env.VITE_API_BASE || "http://localhost:8000";
const map = L.map("map", { minZoom: 2, maxZoom: 8 }).setView([-69.5, 45], 4);
L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", { attribution: "© OpenStreetMap contributors", maxZoom: 8 }).addTo(map);
const concentrationLayer=L.layerGroup().addTo(map), icebergLayer=L.layerGroup().addTo(map), routeLayer=L.layerGroup().addTo(map), stationLayer=L.layerGroup().addTo(map);
let routeStart=null,routeGoal=null,stationData={},currentForecast=3,currentForecastGrid=null,baseGrid=null;
function setStatus(message,ok=false){document.getElementById("status-text").textContent=message;document.getElementById("status-indicator").classList.toggle("ok",ok)}
function concentrationColor(value){const v=Math.max(0,Math.min(1,Number(value)||0)),a=[230,246,250],b=[20,62,82];const c=a.map((x,i)=>Math.round(x+v*(b[i]-x)));return`rgb(${c[0]},${c[1]},${c[2]})`}
function renderSeaIce(grid){baseGrid=grid;const values=currentForecastGrid||grid.concentration;concentrationLayer.clearLayers();const rows=grid.lat.length,cols=grid.lat[0].length,step=Math.max(1,Math.floor(Math.min(rows,cols)/90)),latStep=Math.abs(grid.lat[Math.min(rows-1,1)][0]-grid.lat[0][0])/2||.1,lonStep=Math.abs(grid.lon[0][Math.min(cols-1,1)]-grid.lon[0][0])/2||.25;for(let r=0;r<rows;r+=step){for(let c=0;c<cols;c+=step){const conc=values[r][c];if(conc<.03)continue;const lat=grid.lat[r][c],lon=grid.lon[r][c];L.rectangle([[lat-latStep,lon-lonStep],[lat+latStep,lon+lonStep]],{color:"transparent",fillColor:concentrationColor(conc),fillOpacity:.62,weight:0}).addTo(concentrationLayer)}}}
async function loadSeaIceGrid(){const res=await fetch(`${API_BASE}/api/seaice/grid`);if(!res.ok)throw Error("Sea-ice grid unavailable");const data=await res.json();currentForecastGrid=data.concentration;renderSeaIce(data);document.getElementById("dataset-label").textContent=data.meta?.dataset_kind||"Unknown dataset";document.getElementById("source-note").textContent=data.meta?.source||""}
async function loadForecast(){const res=await fetch(`${API_BASE}/api/seaice/forecast?horizon_days=${currentForecast}`);if(!res.ok)throw Error("Forecast unavailable");const data=await res.json();currentForecastGrid=data.forecast[currentForecast-1];if(baseGrid)renderSeaIce(baseGrid);document.getElementById("forecast-label").textContent=`Forecast day +${currentForecast}`}
async function loadConfig(){const res=await fetch(`${API_BASE}/api/config`);if(!res.ok)throw Error("Configuration unavailable");const data=await res.json();stationData=data.stations||{};stationLayer.clearLayers();Object.entries(stationData).forEach(([name,p])=>L.circleMarker([p.lat,p.lon],{radius:7,color:"#f6f1a8",fillColor:"#f6f1a8",fillOpacity:1,weight:2}).bindPopup(`<b>${name}</b><br>Indian Antarctic research station`).addTo(stationLayer))}
async function loadIcebergs(){const res=await fetch(`${API_BASE}/api/icebergs/projected?hours_ahead=24`);if(!res.ok)throw Error("Iceberg data unavailable");const data=await res.json();icebergLayer.clearLayers();document.getElementById("iceberg-count").textContent=data.icebergs.length;const list=document.getElementById("iceberg-list");list.innerHTML="";data.icebergs.forEach(b=>{L.circleMarker([b.lat,b.lon],{radius:5,color:"#f2a154",fillColor:"#f2a154",fillOpacity:.9,weight:1}).bindPopup(`<b>${b.id}</b><br>Length: ${b.length_km} km<br>Projected +${b.hours_ahead}h: ${b.projected_lat.toFixed(2)}, ${b.projected_lon.toFixed(2)}`).addTo(icebergLayer);L.polyline([[b.lat,b.lon],[b.projected_lat,b.projected_lon]],{color:"#f2a154",weight:1,dashArray:"4,4",opacity:.7}).addTo(icebergLayer);const item=document.createElement("div");item.className="iceberg-item";item.innerHTML=`<span>${b.id}</span><span class="size">${b.length_km} km</span>`;list.appendChild(item)})}
function updateRouteUI(){document.getElementById("start-coord").textContent=routeStart?`${routeStart.lat.toFixed(2)}, ${routeStart.lng.toFixed(2)}`:"—";document.getElementById("goal-coord").textContent=routeGoal?`${routeGoal.lat.toFixed(2)}, ${routeGoal.lng.toFixed(2)}`:"—";document.getElementById("compute-route-btn").disabled=!(routeStart&&routeGoal)}
function selectStation(name){const p=stationData[name];if(!p)return;if(!routeStart||routeGoal){routeStart=L.latLng(p.lat,p.lon);routeGoal=null}else routeGoal=L.latLng(p.lat,p.lon);updateRouteUI();map.setView([p.lat,p.lon],5)}
document.querySelectorAll(".station-btn").forEach(b=>b.addEventListener("click",()=>selectStation(b.dataset.station)));
map.on("click",e=>{if(!routeStart||routeGoal){routeStart=e.latlng;routeGoal=null;routeLayer.clearLayers()}else routeGoal=e.latlng;updateRouteUI()});
document.getElementById("clear-route-btn").addEventListener("click",()=>{routeStart=null;routeGoal=null;routeLayer.clearLayers();document.getElementById("route-result").textContent="";updateRouteUI()});
document.getElementById("compute-route-btn").addEventListener("click",async()=>{const result=document.getElementById("route-result");if(!routeStart||!routeGoal)return;result.textContent="Computing route…";const vessel=document.getElementById("vessel-profile").value;try{const q=new URLSearchParams({start_lat:routeStart.lat,start_lon:routeStart.lng,goal_lat:routeGoal.lat,goal_lon:routeGoal.lng,horizon_days:currentForecast,vessel_profile:vessel});const res=await fetch(`${API_BASE}/api/route?${q}`),data=await res.json();if(!res.ok)throw Error(data.detail||"Route computation failed");routeLayer.clearLayers();const pts=data.path.map(p=>[p.lat,p.lon]);L.polyline(pts,{color:"#4fd8e8",weight:4,opacity:.95}).addTo(routeLayer);L.circleMarker(pts[0],{radius:7,color:"#4fd8e8",fillOpacity:1}).addTo(routeLayer);L.circleMarker(pts[pts.length-1],{radius:7,color:"#9ff6c8",fillOpacity:1}).addTo(routeLayer);result.innerHTML=`<span class="ok">Route found</span><br>${data.distance_km.toFixed(0)} km · mean ice ${(100*data.mean_ice_concentration).toFixed(0)}% · max iceberg risk ${(100*data.max_iceberg_risk).toFixed(0)}%<br><span class="muted">Forecast +${data.horizon_days}d · ${data.vessel_profile}</span>`}catch(e){result.innerHTML=`<span class="err">${e.message}</span>`}});
document.getElementById("horizon-slider").addEventListener("input",async e=>{currentForecast=Number(e.target.value);document.getElementById("horizon-value").textContent=currentForecast;try{await loadForecast()}catch(err){console.error(err);setStatus("Forecast refresh failed")}});
async function init(){try{setStatus("Loading polar data…");await Promise.all([loadConfig(),loadSeaIceGrid()]);await loadForecast();await loadIcebergs();setStatus("Backend online",true)}catch(e){setStatus("Backend unavailable — start FastAPI");console.error(e)}}updateRouteUI();init();
